### ISSUE TITLE
Update version to 1.0.2

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/vsweb-publish#20]
We should update the version to ```1.0.2```

**Comment by georgiosd** [comment]
Is this why AllowUntrustedCertificate is not supported by VS2015 RTM?

**Comment by sayedihashimi** [comment]
@georgiosd yeah that's the reason.

If you would like to use the latest then in the .ps1 file created (under the `Properties\PublishProfiles`) change the version to the following.

```
$publishModuleVersion = '1.0.2-beta1'
```

Then `AllowUntrustedCertificate` should work. Let me know if you have any issues.

**Comment by georgiosd** [comment]
Thank you - what's the preferred way of receiving updates on these scripts?

**Comment by sayedihashimi** [comment]
@georgiosd when you create a publish profile in VS it will use the latest version that it ships with. The idea is that if the script is working for you there's no need to update the version. After that you can update whenever you run into an issue.

**Comment by georgiosd** [comment]
@sayedihashimi It doesn't seem to work :(

**Comment by georgiosd** [comment]
I also had to replace '1.0.1` with `$publishModuleVersion` for it to work

**Comment by sayedihashimi** [comment]
@georgiosd ok glad you got it working.

**Comment by bruceyclee** [comment]
I'm reviewing all issues here. This issue will be closed. If it happens, please re-open it. Thanks.
