### ISSUE TITLE
Publishing not using VS project name to publish package

### ISSUE THREAD

**Issue by dynamiclynk** [aspnet/vsweb-publish#23]
I have a git repo mapped to a local folder with an underscore in the name and VS build output states the package ID is invalid because the repo folder contains an underscore. 

Shouldn't the deployment use the VS project name as the package name instead of using my local repo folder as the package name?

## Build error: ##
*System.ArgumentException: The package ID 'dotnet_subdir_proj' contains invalid characters. Examples of valid package IDs include 'MyPackage' and 'MyPackage.Sample'.
2>     at NuGet.PackageIdValidator.ValidatePackageId(String packageId)*

**Comment by sayedihashimi** [comment]
I'm having a hard tine following this. Can you include steps to reproduce?

**Comment by dynamiclynk** [comment]
Have a project source folder with underscores or some naming convention
that violates nuspec. Then try to build or publish the project, after
renaming the source folder excluding underscores the build succeeded.

-sent from my mobile

**Comment by dynamiclynk** [comment]
I have confirmed this only happens when Project Properties > Build >
Produce outputs on build is checked. Removing the check suppresses the
error and build succeeds.

**Comment by sayedihashimi** [comment]
@BillHiebert I think this is a dnx issue, right?

**Comment by davidfowl** [comment]
> Shouldn't the deployment use the VS project name as the package name instead of using my local repo folder as the package name?

The project name is the folder name. The VS project is irrelevant in most cases. We have a work item to allow changing the project name from the folder name but it's not happening for v1. Can you rename the folder?

**Comment by dynamiclynk** [comment]
Sure I can rename it to get around it. I was just under the impression if the build was trying to generate a nuget package it would use the name of my .xproj, but if this is by design I can bear with it.

**Comment by sayedihashimi** [comment]
@dynamiclynk ok thanks. As @davidfowl mentioned we will later work on a feature where you can specify the name of the project in `project.json`. I'll close this now, please reopen if you think we need more discussion here.
