### ISSUE TITLE
Web.config transforms for setting environmentVariables for httpPlatformHandler

### ISSUE THREAD

**Issue by Schlurcher** [aspnet/vsweb-publish#26]
Hi there, this is probably more a question than an issue.

I'm currently publishing to my own machine using Web Publish. This machine hosts both staging and production environments. Which means both share the same ASPNET_ENV variable and this causes a bit of friction during deployment. I have to manually change the environmentVariable of the httpPlatform according to the deployment target.

What I would much prefer were the ability to use web.config transforms to transform the wwwroot/web.config during publish, for the sole purpose of setting ASPNET_ENV depending on the publish profile.

Is it currently possible to run transforms during publish, or was this ability deemed unnecessary for the new publish process?

**Comment by sayedihashimi** [comment]
Moved to https://github.com/aspnet/Tooling/issues/252 closing here
