### ISSUE TITLE
? re: --no-source flag and "Compile source files into NuGet packages" in VS Publish

### ISSUE THREAD

**Issue by GuardRex** [aspnet/vsweb-publish#27]
RE: VS Publish

Confused a bit on why the setting for "Compile source files into NuGet packages" ... It results in a `dnu publish` command with `--no-source`. I expected the opposite behavior, which means I don't understand what the switch does relative to what the `--no-source` flag means in the command. What am I missing in my understanding?

**Comment by BillHiebert** [comment]
@vijayrkn

**Comment by GuardRex** [comment]
Just to clarify: This is just purely a question of mine: Checking the box for "Compile source files into NuGet packages" does indeed do just that. I'm just wondering why the flag is called "--no-source" because that sounds like it's literally *not* going to produce a NuGet package of the project.

**Comment by vijayrkn** [comment]
Can you create the issue in the dnx repo for the --no-source flag naming issue(https://github.com/aspnet/dnx).I can see how --no-source name can a confusing. That is reason we changed the text in publish dialog to "Compile source files into NuGet packages" rather than no source.

**Comment by GuardRex** [comment]
@vijayrkn Ok, thanks. That makes perfect sense. I was just asking b/c I was just talking to @davidfowl about getting the signing key of an assembly in the right spot in a published app so it would get picked up in the server environment, He said to go "--no-source" to get a full project structure in the published app, and that's when it sort of dawned on me that the name of the flag is kind-of misleading and kind-of doesn't match what the checkbox says with the word "no" in there. I just expected it to go the other way in terms of what the flag did. No worries ... thanks for responding.

Let me leave you with one idea though along these lines. You say that it was best to not show that checkbox as "--no-source" ... yes ... totally get that ... but when @davidfowl said to publish "--no-source", I went looking for that and it took me a little while to figure it out, especially because the wording seems a little backwards. Just as an idea here: Perhaps making the text of the checkbox read like this ...
```
Compile source files into NuGet packages (--no-source)
```
... would solve both situations: let folks know what's going to happen but also explain what switch will be added to the publish command. I'll wait to hear if that's a decent idea before closing; but if that's no good and you want to close, please go ahead and close ... this issue was mostly just about my question on it.

**Comment by vijayrkn** [comment]
@sayedihashimi

**Comment by sayedihashimi** [comment]
Move this issue to https://github.com/aspnet/Tooling/issues/318. The tooling repo is the best place to report all issues related to VS tooling for ASP.NET 5. Closing this issue.
