### ISSUE TITLE
Add Gulp samples for powershell script

### ISSUE THREAD

**Issue by JamesReate** [aspnet/vsweb-publish#28]
It would be nice to have some samples as to how we could use Gulp or other client side pre-processing tools in the publish powershell script. 

Ideally we could just right click publish and the gulp commands that need to be run for our project to be ready to publish would run through the powershell script.

**Comment by GuardRex** [comment]
@JamesReate This is on the way ... it's on the backlog. The idea is that there will be an easy way to add scripts to the VS publish process. See: https://github.com/aspnet/Tooling/issues/195

**Comment by JamesReate** [comment]
Great stuff. Going through the other post.
