### ISSUE TITLE
Calling default-publish.ps1 to create Web Deploy Package?

### ISSUE THREAD

**Issue by Eneuman** [aspnet/vsweb-publish#29]
Hi!

I have searched the entire net but haven't found any information regarding using default-publish.ps1 to publish a ASP.Net 5 site from a artifact drop folder in VSO Release Manager Next.

Is it possible?

I have my site building in a build definition in VSO.
Looking at the logs, it seems like it's using DNU Publish to generate files to a drop location.
Are these files enough to be able to use default-publish.ps1 to publish them to a Azure site?

My main goal is to make a blog post about how to use VSO to build -> package -> test -> drop (artifacts) -> Release manage -> Deploy to Azure

**Comment by sayedihashimi** [comment]
@Eneuman thanks for the note. We don't have package support for ASP.NET 5. I could help you get a MSDeploy package created but I think it may not be needed.

I think you can achieve a similar result by publishing to the file system, and then using the folder as a replacement for the MSDeploy package. 

Here is what I would do.

 1. Create a publish profile in the web project publishing to the file system. (_If you want to skip this step I can help with as well, let me know_)
 1. Create a script that will build the project and publish to the file system with the publish profile created in the previous step.
 1. Execute validation
 1. Publish the folder from step 1 to the remote destination

For the last step you'll call `msdeploy.exe`. You can use the same commands that the publish profile script itself uses. If you look at the publish profile script all it really does is the following.

 1. Ensure that the `publish-module` is loaded. This is shipped in a NuGet package [publish-module](https://www.nuget.org/packages/publish-module) and is also available on machines with VS installed at `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\Publish\Scripts\1.0.1`
 1. Call `Publish-AspNet` with the correct settings to publish

So to load `publish-module` on a machine with VS installed you can execute

```powershell
Import-Module “${env:ProgramFiles(x86)}\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\Publish\Scripts\1.0.1\publish-module.psm1"
```

If the machine doesn't have the publish-module installed you can use `nuget.exe` to extract the nuget package and then call `Import-Module` on `publish-module.psm1` file. You can either do that directly with `nuget.exe` or you can use my open source project [`nuget-powershell`](http://github.com/ligershark/nuget-powershell) to take care of the hard work for you. Here is a snippet to show you how to ensure the module is loaded with `nuget-powershell`.

```powershell
Set-StrictMode -Version Latest


function Load-PublishModule{
    [cmdletbinding()]
    param(
        [Parameter(Position=0)]
        [string]$version = '1.0.2-beta1'
    )
    process{
        # if it's loaded remove and reload
        if(Get-Module publish-module -ErrorAction SilentlyContinue){
            Remove-Module publish-module | Out-Null
        }

        Import-Module (join-path (Get-NuGetPackage -name publish-module -version $version -binpath) 'publish-module.psm1') -DisableNameChecking
    }
}

function Ensure-NuGetPowerShellIsLoaded{
    [cmdletbinding()]
    param(
        $nugetPsMinModVersion = '0.2.3.1'
    )
    process{
        # see if nuget-powershell is available and load if not
        $nugetpsloaded = $false
        if((get-command Get-NuGetPackage -ErrorAction SilentlyContinue)){
            # check the module to ensure we have the correct version
            $currentversion = (Get-Module -Name nuget-powershell).Version
            if( ($currentversion -ne $null) -and ($currentversion.CompareTo([version]::Parse($nugetPsMinModVersion)) -ge 0 )){
                $nugetpsloaded = $true
            }
        }

        if(!$nugetpsloaded){
            (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/ligershark/nuget-powershell/master/get-nugetps.ps1") | iex
        }

        # verify it was loaded
        if(-not (get-command Get-NuGetPackage -ErrorAction SilentlyContinue)){
            throw ('Unable to load nuget-powershell, unknown error')
        }
    }
}

Ensure-NuGetPowerShellIsLoaded
Load-PublishModule

# now you can call publish-aspnet
```

From there you'll need to craft you're call to `Publish-AspNet`. You can see the samples of how to call that using `Get-Help publish-aspnet –Examples` or you can look at the source comments at https://github.com/aspnet/vsweb-publish/blob/master/publish-module.psm1#L246. For example to publish using MSDeploy to an Azure Web Site you'd use a call like the following.

```powershell
Publish-AspNet -packOutput $packOutput -publishProperties @{
     'WebPublishMethod'='MSDeploy'
     'MSDeployServiceURL'='contoso.scm.azurewebsites.net:443';`
     'DeployIisAppPath'='contoso';'Username'='$contoso';'Password'="$env:PublishPwd"}
```

I have some scripts to test startup/publish times that shows this at https://raw.githubusercontent.com/sayedihashimi/publishtests/master/test-startup-times.ps1 and https://github.com/sayedihashimi/publishtests/blob/master/test-publish-times.ps1


Let me know if that helps you or not. And please let me know if you feel that we still need MSDeploy package support.

**Comment by Eneuman** [comment]
Thank you for your very thorough post!
I'm gonna start crafting the script. Ill get back to you as soon as I have some results :)

**Comment by Eneuman** [comment]
Status update :)
I have been able to build and copy the artifacts from the VSO Hosted Build Agent to the drop location and It's looking good.

The problem occur on the Release Manager Agent.
I though I start easy and just try and call a default PublishAspNet5Website.ps1 script


    param($websiteName, $packOutput)
    $website = Get-AzureWebsite -Name $websiteName
    # get the scm url to use with MSDeploy.  By default this will be the second in the array
    $msdeployurl = $website.EnabledHostNames[1]

    $publishProperties = @{'WebPublishMethod'='MSDeploy';
                        'MSDeployServiceUrl'=$msdeployurl;
                        'DeployIisAppPath'=$website.Name;
                        'Username'=$website.PublishingUsername;
                        'Password'=$website.PublishingPassword}

    $publishScript = "${env:ProgramFiles(x86)}\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\Publish\Scripts\default-publish.ps1"


    . $publishScript -publishProperties $publishProperties  -packOutput $packOutput

But I get this error:

2016-01-07T19:24:07.5461815Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\AzurePowerShell\1.0.8\RunAzurePowerShell.ps1
2016-01-07T19:24:08.9966444Z Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1
2016-01-07T19:24:11.5456636Z AzurePSCmdletsVersion= 0.9.8.1
2016-01-07T19:24:11.8335790Z Get-ServiceEndpoint -Name ########## -Context Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.TaskContext
2016-01-07T19:24:56.4203070Z Username= ********
2016-01-07T19:24:56.4213068Z azureSubscriptionId= ###############
2016-01-07T19:24:56.4223066Z azureSubscriptionName= ##############
2016-01-07T19:24:56.4313063Z Add-AzureAccount -Credential $psCredential
2016-01-07T19:24:59.3977833Z Select-AzureSubscription -SubscriptionId #############
2016-01-07T19:24:59.8537995Z ScriptArguments= -$websiteName "Asp5WebBuild" -$packOutput C:\a\6bdfe84f6\Test\drop
2016-01-07T19:24:59.8547994Z ScriptPath= C:\a\6bdfe84f6\Test\drop\PublishAspNet5Website.ps1
2016-01-07T19:24:59.8558001Z scriptCommand= & "C:\a\6bdfe84f6\Test\drop\PublishAspNet5Website.ps1" -$websiteName "Asp5WebBuild" -$packOutput C:\a\6bdfe84f6\Test\drop
2016-01-07T19:25:04.4149362Z ##[error]Cannot index into a null array.
2016-01-07T19:25:04.9265366Z Publishing with publish method [MSDeploy]
2016-01-07T19:25:05.2943357Z ##[error]Cannot find path 'C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\AzurePowerShell\1.0.8\Asp5WebBuild\wwwroot' because it does not exist.
2016-01-07T19:25:05.3093344Z ##[error]An error occurred during publish.
2016-01-07T19:25:05.3093344Z ##[error]You cannot call a method on a null-valued expression.

I have confirmed that it's the command:

       $msdeployurl = $website.EnabledHostNames[1]

that's causes the array null error, so that means that the command:

       $website = Get-AzureWebsite -Name $websiteName

is not working as it should.

I have double checked my settings and cannot find any problems.
Any suggestions on where to look ?

**Comment by Eneuman** [comment]
@sayedihashimi 
I have run into a small problem when I publish my application from my directory to Azure.
It seems like Publish-AspNet does not update my runtime (/approot/runtimes/) folder with the new runtime. I can see that the runtime exists in my artifacts and all other files ar updated.

**Comment by sayedihashimi** [comment]
@eneuman what needs to be updated in runtimes folder? Do you have steps I can follow to reproduce?

**Comment by sayedihashimi** [comment]
@Eneuman just to let you know we recently posted a doc you may be interested in https://docs.asp.net/en/latest/publishing/web-publishing-vs.html. I've also started a wiki for other useful links at https://github.com/aspnet/vsweb-publish/wiki

**Comment by Eneuman** [comment]
@sayedihashimi 
I'm not quite sure, but the HTTP error 500 dissappered after I published from with in Visual Studio. After that my publish from my deploy script worked perfect:)

Try this:
1) Create a ASP.Net 5 MVC Default Project
2) Create a Azure Website, default settings
3) Build and publish your Project using the following command:

    msbuild.exe "YourWeb.xproj" /nologo /m /nr:false /t:"Clean" /t:Build,FileSystemPublish /p:PublishConfiguration=debug /p:PublishOutputPathNoTrailingSlash=C:\temp\myweb /p:PublishDNXVersion=dnx-coreclr-win-x86.1.0.0-rc1-update1 /p:platform="any cpu" /p:configuration="debug" /p:VisualStudioVersion="14.0"

(I have copy and paced from my build task in VSO Build above so you might need to change a few parameters).

4) Now publish your directory to azure like this:

    PublishAspNet5Website.ps1 -websiteName "YourWebSite" -packOutput C:\Temp\myweb

PublushAspNet5WebSite.ps1 can be found here https://github.com/Microsoft/HealthClinic.biz/blob/master/src/MyHealth.Web/PublishAspNet5Website.ps1

I can think of a few things that might be wrong:
* The files in the azure website is not removed before it publishes my files.
* The runtime on the runtime library is not updated
* Some files are missing from the catalog after msbuild has published the files

**Comment by Eneuman** [comment]
@sayedihashimi 
Nice post :)
I'm really looking forward to the "Publishing to an Azure Web App with Continuous Deployment" post.

It would be great to also have VSO Build step support for building and deploying ASP.Net 5 Webs to azure. It looks like it would be possible to change todays "Visual Studio Build" task so It calls a ps1 script instead, and that script checks if its a .Net 5 or a .Net 4 project and calls MSBuild or DNU Build. From what I can tell all the gui parts already exists in the widget :)

**Comment by msiers** [comment]
So I am trying to get this build and deployment configured up in Visual Studio Team Services.

I have successfully built the project in VSTS but when I try and get the publish step working,
I keep getting a Error Parsing the project file on the build step.  I have tried using both a Visual Studio Build and a MSBuild but both build steps are giving the same error.

Any thoughts on why the build is not working properly for me?  Everything builds and runs fine on my local machine.

**Comment by sayedihashimi** [comment]
@msiers can you open a new issue with steps to reproduce? I'm not following you about what's happening.

**Comment by msiers** [comment]
Sure.  Here is the quick summary.  I am trying to follow the steps from the post **https://msdn.microsoft.com/Library/vs/alm/Build/azure/deploy-aspnet5**.   When I execute the build on VSTS, at step 8, I am getting an error message about parsing the xproj file.

I have seen some other posts of people having the same problem but I have not seen any references to a solution.

**Comment by sayedihashimi** [comment]
@msiers please open a separate issue so that we don't clutter this one.
