### ISSUE TITLE
Create vso-agent-task with Publish-AspNet

### ISSUE THREAD

**Issue by damienpontifex** [aspnet/vsweb-publish#31]
The current publish web app in vso-agent-tasks that is used in TFS and VSTS doesn't work well with aspnet5. 

Could a new task be created that utilises this module and the `Publish-AspNet` powershell command to enable reliable publishing of aspnet 5 applications from the new build platform?

**Comment by sayedihashimi** [comment]
@damienpontifex I've never created a vso-agent-task. I believe that after things settle down with ASP.NET 5 that the vso/team build team will make deployment first class, until then it's a bit more complicated.

To answer your question 
>Could a new task be created that utilises this module and the `Publish-AspNet` powershell command to enable reliable publishing of aspnet 5 applications from the new build platform?

`Publish-AspNet` will help simplify automated deployment in any scenario where PowerShell is available. So if you can invoke PowerShell then the answer is yes :) If you create such a task, or need help to automate publishing in general let me know.

FYI we just posted a doc you may be interested in https://docs.asp.net/en/latest/publishing/web-publishing-vs.html. Also take a look at my comments about how the publish module can be loaded in a stand alone script https://github.com/aspnet/vsweb-publish/issues/29#issuecomment-169755934

**Comment by damienpontifex** [comment]
Thanks for the help @sayedihashimi it seems like #29 is following along the same lines as what I'm looking for so will track it there.
