### ISSUE TITLE
Every time I publish to Azure "--configuration debug" is set...

### ISSUE THREAD

**Issue by Cybrosys** [aspnet/vsweb-publish#34]
Every time I publish to Azure "--configuration debug" is set, and I can't seem to find/change anything in my project to change this. I've built using Debug and/or Release but it makes no difference.

**Comment by sayedihashimi** [comment]
Hi @cybrosys, can you clarify what you mean by

>"--configuration debug" is set

**Comment by Cybrosys** [comment]
After doing some more digging, i found the problem. The PublishProfile\*.pubxml file had two tags:
<LastUsedBuildConfiguration />
<LastUsedPlatform />

They never changed when I toggled between Debug and Release build configuration, which meant that when I published to Azure, it published it with debug compilation.

I solved it by editing the file and changing the tags to the following:
<LastUsedBuildConfiguration>Release</LastUsedBuildConfiguration>
<LastUsedPlatform>Any CPU</LastUsedPlatform>

**Comment by vijayrkn** [comment]
If you are publishing from VS, you can set the configuration in the Settings tab. When you invoke the publish command, a solution build is done with the configuration you set in the settings tab and then the assets are published.
