### ISSUE TITLE
How to force Publish-AspNet to use service url as is?

### ISSUE THREAD

**Issue by NickAb** [aspnet/vsweb-publish#45]
I am trying to deploy to localhost IIS using MSDeploy.
When specifying `<MSDeployServiceURL>localhost</MSDeployServiceURL>`, `Publish-AspNet` converts `localhost` to `https://localhost:8172/msdeploy.axd` if  `MSDeployPublishMethod` not set or set to `WMSVC` set, if it is set to `InProc`, then it fails to create uri `"Invalid URI: The format of the URI could not be determined."`.

But if I copy logged msdeploy command and replace `ComputerName` with plain `'localhost'`, then everything works ok. How can I force `Publish-AspNet` to use plain `localhost as `ComputerName`?

**Comment by sayedihashimi** [comment]
@vijayrkn is looking at this I think.

TFS: 224918
I've added this to our internal TFS, we will reply back here soon.

**Comment by vijayrkn** [comment]
https://github.com/aspnet/vsweb-publish/commit/309acef0875c51ca1e5c0787e776d84b615a8be3

You can set this property with the latest script. 
`<UseMSDeployServiceURLAsIs>true</UseMSDeployServiceURLAsIs>`
