### ISSUE TITLE
Passing more arguments to webdeploy.exe

### ISSUE THREAD

**Issue by mrahhal** [aspnet/vsweb-publish#49]
I'm reading the source for `Publish-AspNet` and there seems to be no way for passing more arguments to `webdeploy.exe`.

I have a publish profile setup and I want to pass `-allowUntrusted` to `webdeploy.exe`, how do I do that?

**Comment by vijayrkn** [comment]
In the publish profile you can add 
```
<AllowUntrustedCertificate>true</AllowUntrustedCertificate>
```

**Comment by mrahhal** [comment]
Thanks. This will do.
