### ISSUE TITLE
How to set DesktopBuildPackageLocation from msbuild

### ISSUE THREAD

**Issue by jimoneil** [aspnet/vsweb-publish#52]
I'm trying to automate packaging of an ASP.NET 5 app for deployment to Azure.  Right now, I'm running
_msbuild t:/publishpackage_ which creates the package, but I'd like to specify a different location.  It looks like the **DesktopBuildPackageLocation **parameter will do that, but I'm having trouble figuring out how to set that at the msbuild (not msdeploy) command.  I've put the setting into a pubxml file, but it continues to go to the directory specified in the file here:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Powershell\1.0.1\package.pubxml

namely:
    `<DesktopBuildPackageLocation>$(OutDir)\$(Configuration)\MSDeployPackage\$(MSBuildProjectName).zip</DesktopBuildPackageLocation>`

Should I be able to override this with my own pubxml like:

`msbuild foo.xproj /t:packagepublish /p:publishfile=myfile.pubxml`

**Comment by vijayrkn** [comment]
If you are planning to use the default profile, you should be able to override the settings by passing it as a parameter to msbuild.
```msbuild foo.xproj /t:packagepublish /p:DesktopBuildPackageLocation="c:\Temp\package.zip"```

or if you want to use your own profile, that will also work. You can set the value in pubxml and pass the 
```msbuild foo.xproj /t:packagepublish /p:publishProfile=myfile.pubxml ```

**Comment by jimoneil** [comment]
well, I swear I had tried both of those to no avail, but indeed it seems to work now.  I also happened across the PackagePubXmlFile property which also seemed to work.  Not sure why I wasn't getting it working earlier, perhaps not picking up the right msbuild targets.   Thank you very much!
