### ISSUE TITLE
Publishing with Staging environment

### ISSUE THREAD

**Issue by beho** [aspnet/vsweb-publish#68]
Hi,

I have a problem (or misunderstanding) with publishing using VS to IIS in Staging environment. It might be caused by using ASP.NET Core RC1 before.

In RC1 appsettings for all environments were copied to server, "HOSTING:ENVIRONMENT" environment variable was set system-wide and website then used this environment.

Now trying to deploy project migrated to ASP.NET Core RTM I recreated publishing profile, changed environment variable name to "ASPNETCORE_ENVIRONMENT" on the server and hit publish. I see only generated appsettings.json in root deployment directory that contains Production values used.

Now I cannot figure out what I should do to switch (default) Production to Staging for this publishing profile.

Thanks in advance!

**Comment by vijayrkn** [comment]
Can you make sure that the appsettings for all environments is available in project.json under publishOptions?

`  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },`

**Comment by beho** [comment]
That's it. Thanks!
