### ISSUE TITLE
Support of ExcludeFilesFromDeployment of standard pubxml files

### ISSUE THREAD

**Issue by GregoryOtt** [aspnet/vsweb-publish#73]
Today, the xml tags _ExcludeFilesFromDeployment_ and _ExcludeFoldersFromDeployment_ described [here](https://msdn.microsoft.com/en-us/library/ee942158(v=vs.110).aspx#Anchor_0) are not working for asp.net core projects. FYI, see this [Stackoverflow question](http://stackoverflow.com/questions/34352482/how-to-exclude-files-from-being-published-in-asp-net-5-asp-net-core).

Do you plan to support those tags of the standard pubxml files?

The _publishOptions_ object of project.json is not sufficient as it can't be a child of the _configuration_. For instance, if I want to exclude an environment appsettings file according to current profile/configuration, how can I do this?
Today, as a workaround, I edit the _profile_-publish.ps1 by manually adding entries to the _ExcludeFiles_ of the _$publishProperties_
```
$publishProperties['ExcludeFiles'] += @(
		@{'absolutepath'='appsettings.Dev.json'}
	)
```

**Comment by sayedihashimi** [comment]
We are moving from PowerShell to MSBuild so this may work after the next release. With that being said, the existing publish support (for ASP.NET 4) is poorly engineered so we are starting from scratch. You may need to change to use a different item name, but the scenario will be supported via an MSBuild Item like before.

**Comment by GregoryOtt** [comment]
Do you have any roadmap to provide? Anyway, thx for the answer.

**Comment by sayedihashimi** [comment]
@GregoryOtt we don't really have a roadmap for publish, but in the next release it will be MSBuild based and we should have support for excluding files as mentioned here.
